USE QUANLYSINHVIEN;

SELECT*FROM STUDENT;
SELECT*FROM STUDENT WHERE StudentName LIKE 'H%';
SELECT*FROM CLASS WHERE StartDate LIKE '%-12-%';
UPDATE STUDENT SET ClassID = 2 WHERE StudentName = 'Hung'; 
SELECT StudentName,SubName,Mark 
FROM STUDENT S JOIN MARK M ON M.StudentID = S.StudentID JOIN SUBJECT_SCHOOL SS ON M.SubId = SS.SubID
ORDER BY MARK DESC;