USE QUANLYBANHANG;

INSERT INTO CUSTOMER(cName,cAge) VALUES 
('Minh Quan',18),
('Ngoc Oanh',20),
('Hong Ha',50)
;
INSERT INTO ORDERS(cID,oDate,oTatalPrice) VALUES
(1,'2006-03-21',NULL),
(2,'2006-03-23',NULL),
(1,'2006-03-16',NULL)
;

INSERT INTO PRODUCT (pNAME,pPRICE) VALUES
('May Giat',3),
('Tu Lanh',5),
('Dieu Hoa',7),
('Quat',1),
('Bep Dien',2)
;

INSERT INTO ORDERDETAIL (oID,pID,odQTY) VALUES
(1,1,3),
(1,3,7),
(1,4,2),
(2,1,1),
(3,1,8),
(2,5,4),
(2,3,3)
;

SELECT oID,oDate,oTatalPrice FROM ORDERS;

SELECT cName,pNAME,odQTY
FROM CUSTOMER C JOIN ORDERS O ON C.cID = O.cID JOIN ORDERDETAIL OD ON O.oID = OD.oID JOIN PRODUCT P ON OD.pID = P.pID;

SELECT cID,cName FROM CUSTOMER C WHERE C.cID NOT IN (SELECT cID FROM ORDERS);
SELECT cID,cName FROM CUSTOMER C  WHERE NOT  (SELECT cID FROM ORDERS O WHERE C.cID=O.cID);

SELECT O.oID,O.oDate,SUM(P.pPRICE*OD.odQTY) AS TOTAL
FROM ORDERS O JOIN ORDERDETAIL OD ON O.oID = OD.oID JOIN PRODUCT P ON OD.pID = P.pID 
GROUP BY O.oID;